openapi: 3.0.0
info:
  title: Flask CMS API
  description: API for Flask CMS
  version: 1.0.0
paths:
  /api:
    get:
      summary: Fetch some data
      responses:
        '200':
          description: Successful response
